### ISSUE TITLE
Implement RxJava and MVP Pattern

### ISSUE THREAD

**Issue by kadekdaprin** [omrobbie/CatalogueMovie#1]
This is a great application, but I read that we can use a simpler way to use asynchronous programming such as RxJava. I learn that we can separate the process business and the UI by using a design pattern called MVP. I would love to see this application implement RxJava and MVP Pattern in the near future.
Thanks

**Comment by dekzitfz** [comment]
me too

**Comment by omrobbie** [comment]
@codeapin @dekzitfz We'll see how's "GOD" implement that :rofl:

**Comment by dekzitfz** [comment]
OMG! Cant wait to see his live coding session !!!

**Comment by dekzitfz** [comment]
is this issue really closed? I think we need more proper testing here!?
